/*
 * This source file was generated by the Gradle 'init' task
 */
package io.zimran.translator

import org.gradle.api.Plugin
import org.gradle.api.Project
import java.io.File
import java.util.Properties

class TranslatorPlugin : Plugin<Project> {
    override fun apply(project: Project) {

        project.tasks.register("translateResources") { task ->
            task.group = "zimran"
            task.doLast {

                val localProperties = File(project.rootDir, "local.properties")
                val properties = Properties()

                if (localProperties.exists()) {
                    properties.load(localProperties.inputStream())
                    val openAiKey = properties.getProperty("OPEN_AI_KEY")

                    translate(openAiKey, project.rootDir)
                }
            }

        }
    }
}
